---
    - name: Update dnf package cache
      ansible.builtin.dnf:
        update_cache: true

    - name: Ports freischalten
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: enabled
        zone: public
        permanent: true
        immediate: true
      loop: "{{ k8s_worker_ports }}"

    - name: Get kubeadm join command
      command: sudo kubeadm token create --print-join-command
      delegate_to: 192.168.1.10
      register: join_command

    - name: Execute join command
      command: "{{ join_command.stdout }} --ignore-preflight-errors=NumCPU,Mem"
    - name: Disable RX and TX offloading on cni0
      ansible.builtin.command: ethtool -K cni0 tx off rx off
      become: true

    - name: Disable RX and TX offloading on flannel.1
      ansible.builtin.command: ethtool -K flannel.1 tx off rx off
      become: true