all:
  children: 
    control-plane:
      hosts:
        192.168.1.10:
          ansible_user: nufuk
          custom_hostname: k8s-control-plane
    workers:
      hosts:
        192.168.1.20:
          ansible_user: nufuk
          custom_hostname: k8s-worker01
        192.168.1.30:
          ansible_user: nufuk
          custom_hostname: k8s-worker02
