---
  - name: Kopiere die ipaddresspool auf den Server
    ansible.builtin.copy:
      src: ipaddresspool.yml
      dest: /tmp/ipaddresspool.yml
      mode: '0644'

  - name: Apply ipaddresspool manifest via kubectl
    ansible.builtin.shell: "sudo kubectl apply -f /tmp/ipaddresspool.yml"
    register: kubectl_apply
    changed_when: "'created' in kubectl_apply.stdout or 'configured' in kubectl_apply.stdout"
    retries: 5
    delay: 30

  - name: Kopiere die l2advertisement auf den Server
    ansible.builtin.copy:
      src: l2advertisement.yml
      dest: /tmp/l2advertisement.yml
      mode: '0644'

  - name: Apply l2advertiesment manifest via kubectl
    ansible.builtin.shell: "sudo kubectl apply -f /tmp/l2advertisement.yml"
    register: kubectl_apply
    changed_when: "'created' in kubectl_apply.stdout or 'configured' in kubectl_apply.stdout"
    retries: 3
    delay: 10

  - name: create argocd namespace
    ansible.builtin.shell: "kubectl create namespace argocd"
    register: kubectl_apply
    changed_when: "'created' in kubectl_apply.stdout or 'configured' in kubectl_apply.stdout"
    retries: 3
    delay: 10

  - name: apply argocd manifest
    ansible.builtin.shell: "sudo kubectl apply -n argocd --server-side --force-conflicts -f {{ argocd_manifest_url }}"
    register: kubectl_apply
    changed_when: "'created' in kubectl_apply.stdout or 'configured' in kubectl_apply.stdout"
    retries: 3
    delay: 10

  - name: Kopiere die argocd_lb_patch auf den Server
    ansible.builtin.copy:
      src: argocd_lb_patch.yml
      dest: /tmp/argocd_lb_patch.yml
      mode: '0644'

  - name: Patch Argocd svc with type Loadbalacner and IP
    ansible.builtin.shell: "sudo kubectl patch svc argocd-server -n argocd --patch-file /tmp/argocd_lb_patch.yml"
    register: kubectl_apply
    changed_when: "'created' in kubectl_apply.stdout or 'configured' in kubectl_apply.stdout"
    retries: 3
    delay: 10

#  - name: helm add piraeus operator
#    ansible.builtin.command:
#      cmd: helm repo add piraeus-charts https://piraeus.io; helm repo update
#    register: init_helm
#    become: true

#  - name: Kopiere die linstor-values-storage auf den Server
#    ansible.builtin.copy:
#      src: linstor-values.yaml
#      dest: /tmp/linstor-values.yaml
#      mode: '0644'

  - name: Helm install piraeus datastore
    ansible.builtin.command:
      cmd: helm upgrade --install --create-namespace --namespace piraeus-datastore piraeus-operator oci://ghcr.io/piraeusdatastore/piraeus-operator/piraeus --set installCRDs=true --wait
    register: install_piraeus_operator
    become: true

  - name: Helm install piraeus linstor on cluster
    ansible.builtin.command:
      cmd: helm upgrade --install --namespace piraeus-datastore linstor-cluster oci://ghcr.io/piraeusdatastore/helm-charts/linstor-cluster
    register: install_piraeus_operator
    become: true

  - name: Kopiere die linstor-sc auf den Server
    ansible.builtin.copy:
      src: linstor-sc.yaml
      dest: /tmp/linstor-sc.yaml
      mode: '0644'

  - name: Apply linstor sc file
    ansible.builtin.shell: "sudo kubectl apply -f /tmp/linstor-sc.yaml"
    register: kubectl_apply
    changed_when: "'created' in kubectl_apply.stdout or 'configured' in kubectl_apply.stdout"
    retries: 3
    delay: 10
