---


  - name: Kopiere die ipaddresspool auf den Server
    ansible.builtin.copy:
      src: ipaddresspool.yml
      dest: /tmp/ipaddresspool.yml
      mode: '0644'

  - name: Apply ipaddresspool manifest via kubectl
    ansible.builtin.shell: "sudo kubectl apply -f /tmp/ipaddresspool.yml"
    register: kubectl_apply
    changed_when: "'created' in kubectl_apply.stdout or 'configured' in kubectl_apply.stdout"
    retries: 5
    delay: 30

  - name: Kopiere die l2advertisement auf den Server
    ansible.builtin.copy:
      src: l2advertisement.yml
      dest: /tmp/l2advertisement.yml
      mode: '0644'

  - name: Apply l2advertiesment manifest via kubectl
    ansible.builtin.shell: "sudo kubectl apply -f /tmp/l2advertisement.yml"
    register: kubectl_apply
    changed_when: "'created' in kubectl_apply.stdout or 'configured' in kubectl_apply.stdout"
    retries: 3
    delay: 10
